added genres and search by genre function
Breach97/library pull request #10
Opened 2021-12-07 02:37 UTC by arbone

I added all the genres to all books and to let people find books by genres I added a specific function as my other colleagues did. Although I have some problem with the function because I tried but it does not run perfectly. All the data is correct but still I have problems.

2021-12-07 02:46 UTC, arbone commented
Maybe I found out the error, I forgot to add the line "from library import check_genre" (which I added later on)... this can be the answer but I am not quite sure. So I think I need help on this on.

2021-12-07 09:29 UTC, FPolin22 reviewed
I tried to correct it on my own, I find a mistake and you can correct it by just deleting it from line 131 to 133 (last if function), if you can't run it correctly I will send you the correct pull request

2021-12-07 18:09 UTC, Breach97 requested changes
Made 2 comments, check them out at lines 119 and 129

2021-12-07 18:09 UTC, Breach97 commented on library.py
> +def check_genre(book_genre):
Are you sure that `book_genre` in the parenthesis is correct?  Try `genre` and see if it fix the bug

2021-12-07 18:09 UTC, Breach97 commented on library.py
>          if year == pub_year:
**From line 129 to 131**  lines of code are the repetition of lines 112-114. you should **delete** them

2021-12-08 01:03 UTC, arbone commented on library.py
>          if year == pub_year:
Thanks, this should be it

2021-12-08 01:11 UTC, arbone commented on library.py
> +def check_genre(book_genre):
Yes I think it is correct as I followed the other functions

2021-12-08 01:12 UTC, arbone commented on library.py
> +def check_genre(book_genre):
But I accept any suggestions

2021-12-08 01:36 UTC, Breach97 commented on library.py
> +def check_genre(book_genre):
I think that is the error, you can test it locally to see if it works (y)

2021-12-08 09:53 UTC, FPolin22 commented
In local, it works perfectly

2021-12-09 13:42 UTC, arbone commented
I had some issues with the code because in my files I had some additional code inserted by mistake from another team member, it was absolutely not a problem. I solved it by myself. Now I will try it locally and the write a comment here.

2021-12-09 14:12 UTC, arbone commented on library.py
> +def check_genre(book_genre):
There wasn't any error there, but thanks for the suggestion

2021-12-09 14:15 UTC, arbone commented
Tried the code locally and it works. Ready to merge

2021-12-10 08:21 UTC, arbone commented
Waiting for the “ok to merge” from both of my groupmates to merge it. When I receive it, I will merge it.

2021-12-10 13:32 UTC, merged